steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Populating Maven cache from bucket'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/hmf-cloud-sdk/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'

  - name: 'maven:3-jdk-11'
    id: 'Deploying to Maven'
    entrypoint: mvn
    args: ['deploy', '-B']
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
timeout: 4800s
options:
  machineType: 'E2_HIGHCPU_8'
